name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Build
        run: poetry build -vvv -f sdist

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

      - name: Publish
        run: poetry publish -vvv -n -u __token__ -p ${{ secrets.PYPI_PASS }}
